apiVersion: adl.dev/v1
kind: Agent
metadata:
  name: grafana-agent
  description: A2A agent server for grafana dashboards automation tasks
  version: 0.1.0
spec:
  capabilities:
    streaming: true
    pushNotifications: false
    stateTransitionHistory: false
  config:
    grafana:
      deployEnabled: false
      url: ""
      apiKey: ""
      orgID: ""
  services:
    grafana:
      type: service
      interface: Grafana
      factory: NewGrafanaService
      description: Grafana service for accessing Grafana API
  agent:
    provider: ""
    model: ""
    systemPrompt: |
      You are a Grafana expert. Your role is to guide users in designing highly effective, visually clear, and actionable dashboards.
      You provide best practices for data visualization, panel configuration, query optimization, alerting, and overall dashboard usability.
      Always offer practical examples and explain the reasoning behind your recommendations.
  artifacts:
    enabled: true
  skills:
    - id: create_dashboard
      name: create_dashboard
      inject:
        - logger
        - grafana
        - config.grafana
      description: Creates a Grafana dashboard with specified panels, queries, and configurations
      tags:
        - grafana
        - dashboard
        - visualization
      schema:
        type: object
        properties:
          dashboard_title:
            type: string
            description: The title of the Grafana dashboard
          description:
            type: string
            description: Description of what the dashboard monitors or displays
          grafana_url:
            type: string
            description: Grafana server URL (overrides default configuration if provided)
          tags:
            type: array
            items:
              type: string
            description: Tags to categorize the dashboard
          panels:
            type: array
            description: Array of panel configurations (title, type, queries, etc.)
            items:
              type: object
          time_range:
            type: object
            description: Default time range for the dashboard (from, to)
            properties:
              from:
                type: string
              to:
                type: string
          refresh_interval:
            type: string
            description: Auto-refresh interval (e.g., "5s", "1m", "5m")
          variables:
            type: array
            description: Dashboard template variables for dynamic queries
            items:
              type: object
        required:
          - dashboard_title
          - panels
      output:
        type: artifact
        description: Returns the dashboard JSON configuration as an artifact
  server:
    port: 8080
    debug: false
  language:
    go:
      module: github.com/inference-gateway/grafana-agent
      version: "1.25"
  scm:
    provider: github
    url: https://github.com/inference-gateway/grafana-agent
    github_app: true
    issue_templates: true
  sandbox:
    flox:
      enabled: true
