// Code generated by ADL CLI v0.43.2. DO NOT EDIT.
// This file was automatically generated from an ADL (Agent Definition Language) specification.
// Manual changes to this file may be overwritten during regeneration.

package main

import (
	"bytes"
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"path/filepath"
	"sort"
	"strings"
	"syscall"

	envconfig "github.com/sethvargo/go-envconfig"
	cobra "github.com/spf13/cobra"
	zap "go.uber.org/zap"
	yaml "gopkg.in/yaml.v3"

	server "github.com/inference-gateway/adk/server"

	config "github.com/inference-gateway/grafana-agent/config"
	tools "github.com/inference-gateway/grafana-agent/tools"

	grafana "github.com/inference-gateway/grafana-agent/internal/grafana"
	logger "github.com/inference-gateway/grafana-agent/internal/logger"
	promql "github.com/inference-gateway/grafana-agent/internal/promql"
)

// Version, AgentName and AgentDescription are injected at build time
// via `-ldflags "-X 'main.Version=...'"` (see Dockerfile). They default
// to the values declared in the ADL.
var (
	Version          = "0.2.2"
	AgentName        = "grafana-agent"
	AgentDescription = "A2A agent server for grafana dashboards automation tasks"
)

// skillsDir is the directory the runtime scans for skill manifests at
// startup. Override with A2A_SKILLS_DIR.
const skillsDir = "skills"

// loadSkillsManifest walks the configured skills directory, reads each
// <skill>/SKILL.md, extracts the YAML frontmatter (name + description),
// and returns an `AVAILABLE SKILLS:` block to append to the system
// prompt. SKILL.md bodies are NOT inlined - the model must call the
// Read tool to load a skill's playbook on demand. Returns "" when the
// directory is missing or has no valid manifests.
func loadSkillsManifest(dir string) (string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}

	dirs := make([]string, 0, len(entries))
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dirs = append(dirs, e.Name())
	}
	sort.Strings(dirs)

	type skillFrontmatter struct {
		Name        string `yaml:"name"`
		Description string `yaml:"description"`
	}

	var manifest strings.Builder
	for _, id := range dirs {
		path := filepath.Join(dir, id, "SKILL.md")
		data, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return "", err
		}
		fmBytes, ok := extractFrontmatter(data)
		if !ok {
			continue
		}
		var fm skillFrontmatter
		if err := yaml.Unmarshal(fmBytes, &fm); err != nil {
			continue
		}
		if fm.Name == "" || fm.Description == "" {
			continue
		}
		if manifest.Len() == 0 {
			manifest.WriteString("AVAILABLE SKILLS:\n")
			manifest.WriteString("Skills are reusable instructions for specific tasks. When a task matches a\n")
			manifest.WriteString("skill's description, read the SKILL.md file at the listed path using the Read\n")
			manifest.WriteString("tool, then follow its instructions.\n\n")
		}
		fmt.Fprintf(&manifest, "- %s: %s\n  Path: %s\n", fm.Name, fm.Description, path)
	}
	return manifest.String(), nil
}

// extractFrontmatter returns the bytes between the opening and closing
// `---` fences of a SKILL.md file (without including the fences
// themselves). The second return value is false when no frontmatter is
// found.
func extractFrontmatter(content []byte) ([]byte, bool) {
	bom := []byte{0xEF, 0xBB, 0xBF}
	buf := bytes.TrimPrefix(content, bom)
	buf = bytes.TrimLeft(buf, "\r\n\t ")
	if !bytes.HasPrefix(buf, []byte("---")) {
		return nil, false
	}
	rest := buf[3:]
	rest = bytes.TrimLeft(rest, "\r\n")
	idx := bytes.Index(rest, []byte("\n---"))
	if idx < 0 {
		return nil, false
	}
	return rest[:idx], true
}

// newRootCmd builds the top-level CLI for the agent binary. The
// generated binary is a real CLI: `<bin> --version`, `<bin> --help`,
// and `<bin> start` are all supported. Subcommands are added in
// dedicated constructors so they can be unit-tested in isolation.
func newRootCmd() *cobra.Command {
	root := &cobra.Command{
		Use:           AgentName,
		Short:         AgentDescription,
		Long:          AgentDescription + "\n\nThis is an A2A (Agent-to-Agent) protocol server. Use the `start` subcommand to run it.",
		Version:       Version,
		SilenceUsage:  true,
		SilenceErrors: true,
	}
	root.AddCommand(newStartCmd())
	return root
}

// newStartCmd returns the `start` subcommand which boots the A2A
// server and blocks until SIGINT/SIGTERM.
func newStartCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "start",
		Short: "Start the A2A server",
		Long:  "Start the A2A server and block until SIGINT or SIGTERM is received.",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runStart(cmd.Context())
		},
	}
}

// runStart contains the original agent bootstrap. It is exported as a
// dedicated function so the cobra command stays a thin shell - easier
// to test, easier to embed.
func runStart(ctx context.Context) error {
	var cfg config.Config
	if err := envconfig.Process(ctx, &cfg); err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	// Initialize logger
	l, err := logger.NewLogger(ctx, &cfg)
	if err != nil {
		return fmt.Errorf("failed to initialize logger: %w", err)
	}

	l.Info("starting "+AgentName+" agent", zap.String("version", Version), zap.Bool("debug", cfg.A2A.Debug))
	l.Debug("loaded configuration", zap.Any("config", cfg))

	resolvedSkillsDir := skillsDir
	if v := os.Getenv("A2A_SKILLS_DIR"); v != "" {
		resolvedSkillsDir = v
	}
	skillsPrompt, err := loadSkillsManifest(resolvedSkillsDir)
	if err != nil {
		l.Warn("failed to load skills manifest, continuing without them", zap.Error(err))
	} else if skillsPrompt != "" {
		l.Info("loaded skills manifest into system prompt", zap.String("dir", resolvedSkillsDir))
	}

	// Initialize services
	grafanaSvc, err := grafana.NewGrafanaService(l, &cfg)
	if err != nil {
		l.Error("failed to initialize grafana service", zap.Error(err))
		return fmt.Errorf("failed to initialize grafana service: %w", err)
	}
	promqlSvc, err := promql.NewPromQLService(l, &cfg)
	if err != nil {
		l.Error("failed to initialize promql service", zap.Error(err))
		return fmt.Errorf("failed to initialize promql service: %w", err)
	}

	// Create toolbox with default tools (like input_required, create_artifact etc)
	toolBox := server.NewDefaultToolBox(&cfg.A2A.AgentConfig.ToolBoxConfig)

	// Register Read built-in
	readTool, err := tools.NewReadTool(ctx, l)
	if err != nil {
		return fmt.Errorf("failed to construct Read tool: %w", err)
	}
	toolBox.AddTool(readTool)
	l.Info("registered built-in: Read")

	// Register discover_metrics tool
	discoverMetricsTool := tools.NewDiscoverMetricsTool(l, promqlSvc)
	toolBox.AddTool(discoverMetricsTool)
	l.Info("registered tool: discover_metrics (Discovers available metrics from a Prometheus endpoint with optional filtering)")

	// Register generate_promql_queries tool
	generatePromqlQueriesTool := tools.NewGeneratePromqlQueriesTool(l, promqlSvc)
	toolBox.AddTool(generatePromqlQueriesTool)
	l.Info("registered tool: generate_promql_queries (Generates PromQL query suggestions for given metric names by querying Prometheus metadata)")

	// Register validate_promql_query tool
	validatePromqlQueryTool := tools.NewValidatePromqlQueryTool(l, promqlSvc)
	toolBox.AddTool(validatePromqlQueryTool)
	l.Info("registered tool: validate_promql_query (Validates a PromQL query against a Prometheus server)")

	// Register create_dashboard tool
	createDashboardTool := tools.NewCreateDashboardTool(l, grafanaSvc, &cfg.Grafana)
	toolBox.AddTool(createDashboardTool)
	l.Info("registered tool: create_dashboard (Creates a Grafana dashboard with specified panels, queries, and configurations)")

	// Register deploy_dashboard tool
	deployDashboardTool := tools.NewDeployDashboardTool(l, grafanaSvc, &cfg.Grafana)
	toolBox.AddTool(deployDashboardTool)
	l.Info("registered tool: deploy_dashboard (Deploys a dashboard JSON to Grafana (Cloud or self-hosted))")

	llmClient, err := server.NewOpenAICompatibleLLMClient(&cfg.A2A.AgentConfig, l)
	if err != nil {
		return fmt.Errorf("failed to create LLM client: %w", err)
	}

	systemPrompt := `You are a Grafana expert. Your role is to guide users in designing highly effective, visually clear, and actionable dashboards.
You provide best practices for data visualization, panel configuration, query optimization, alerting, and overall dashboard usability.
Always offer practical examples and explain the reasoning behind your recommendations.

When using Prometheus-related tools:
- Use the PROMETHEUS_URL environment variable for prometheus_url parameters (default: http://prometheus.grafana-agent.svc.cluster.local:9090)
- The Prometheus server is available at this internal Kubernetes service URL

When using Grafana-related tools:
- Use the GRAFANA_URL environment variable for grafana_url parameters if not explicitly provided by the user
`
	if skillsPrompt != "" {
		systemPrompt = systemPrompt + "\n\n" + skillsPrompt
	}

	agent, err := server.NewAgentBuilder(l).
		WithConfig(&cfg.A2A.AgentConfig).
		WithLLMClient(llmClient).
		WithToolBox(toolBox).
		WithMaxChatCompletion(cfg.A2A.AgentConfig.MaxChatCompletionIterations).
		WithSystemPrompt(systemPrompt).
		Build()
	if err != nil {
		return fmt.Errorf("failed to create agent: %w", err)
	}

	a2aServer, err := server.NewA2AServerBuilder(cfg.A2A, l).
		WithAgent(agent).
		WithAgentCardFromFile(".well-known/agent-card.json", map[string]any{
			"name":        AgentName,
			"version":     Version,
			"description": AgentDescription,
			"url":         cfg.A2A.AgentURL,
		}).
		WithDefaultBackgroundTaskHandler().
		WithDefaultStreamingTaskHandler().
		Build()
	if err != nil {
		return fmt.Errorf("failed to create A2A server: %w", err)
	}

	go func() {
		l.Info("starting A2A server", zap.String("port", cfg.A2A.ServerConfig.Port))
		if err := a2aServer.Start(ctx); err != nil {
			l.Fatal("server failed to start", zap.Error(err))
		}
	}()

	l.Info("grafana-agent agent running successfully",
		zap.String("port", cfg.A2A.ServerConfig.Port))

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	l.Info("shutdown signal received, gracefully stopping server...")
	a2aServer.Stop(ctx)
	l.Info("grafana-agent agent stopped")
	return nil
}

func main() {
	ctx := context.Background()
	if err := newRootCmd().ExecuteContext(ctx); err != nil {
		log.Fatal(err)
	}
}
