// Code generated by ADL CLI v0.25.0. DO NOT EDIT.
// This file was automatically generated from an ADL (Agent Definition Language) specification.
// Manual changes to this file may be overwritten during regeneration.

package config

import (
	serverConfig "github.com/inference-gateway/adk/server/config"
)

// Config represents the application configuration
type Config struct {
	// Core application settings
	Environment string `env:"ENVIRONMENT"`

	// A2A configuration (all A2A_ prefixed vars)
	A2A serverConfig.Config `env:",prefix=A2A_"`

	// Custom configuration sections
	Grafana GrafanaConfig `env:",prefix=GRAFANA_"`
}

// GrafanaConfig represents the grafana configuration
type GrafanaConfig struct {
	APIKey        string `env:"API_KEY"`
	DeployEnabled bool   `env:"DEPLOY_ENABLED,default=false"`
	OrgID         string `env:"ORG_ID"`
	URL           string `env:"URL"`
}
