// Code generated by ADL CLI v0.24.4. DO NOT EDIT.
// This file was automatically generated from an ADL (Agent Definition Language) specification.
// Manual changes to this file may be overwritten during regeneration.

package config

import (
	serverConfig "github.com/inference-gateway/adk/server/config"
)

// Config represents the application configuration
type Config struct {
	// Core application settings
	Environment string `env:"ENVIRONMENT"`

	// A2A configuration (all A2A_ prefixed vars)
	A2A serverConfig.Config `env:",prefix=A2A_"`

	// Grafana configuration
	Grafana GrafanaConfig `env:",prefix=GRAFANA_"`
}

// GrafanaConfig represents Grafana deployment configuration
type GrafanaConfig struct {
	// Enable/disable Grafana deployments (default: false for safety)
	DeployEnabled bool `env:"DEPLOY_ENABLED" envDefault:"false"`
	// Grafana server URL (optional, can be overridden in prompts)
	URL string `env:"URL"`
	// Grafana API key or service account token
	APIKey string `env:"API_KEY"`
	// Organization ID (default: 1)
	OrgID int `env:"ORG_ID" envDefault:"1"`
}
